drivedb.h: move to new directory and add version info during build
Move 'lib/drivedb.h' to new directory 'drivedb'.

Create 'lib/drivedb.h' with enhanced "VERSION: ..." string during build.
This fixes 'update-smart-drivedb --install' which failed due to the now
missing SVN Id string.
Adjust URLs for 'update-smart-drivedb --main'.

'export SMARTMONTOOLS_TEST_BUILD=1' is now required for builds from
'git clone --depth=1'.  Update workflows accordingly.

Signed-off-by: Christian Franke <christian.franke@t-online.de>

diff --git a/lib/Makefile.am b/lib/Makefile.am
--- a/lib/Makefile.am
+++ b/lib/Makefile.am
@@ -29,6 +29,11 @@ if NEED_REGEX
 AM_CPPFLAGS += -I$(top_srcdir)/include/smartmon/regex -D_REGEX_STANDALONE
 endif
 
+# Suppress 'echo' if './configure --enable-silent-rules' or 'make V=0' is used.
+# Variables AM_V_* are provided by automake >= 1.13.
+ECHO_V = ! $(AM_V_P) || echo
+ECHO_V_GEN = @$(AM_V_P) || echo '  GEN      $@'; $(ECHO_V)
+
 if INSTALL_DEVEL_LIB
 
 lib_LTLIBRARIES = libsmartmon.la
@@ -52,7 +57,6 @@ libsmartmon_la_SOURCES = \
         dev_interface.cpp \
         dev_jmb39x_raid.cpp \
         dev_tunnelled.h \
-        drivedb.h \
         farmcmds.cpp \
         knowndrives.cpp \
         nvmecmds.cpp \
@@ -129,6 +133,32 @@ endif
 if ENABLE_DRIVEDB
 drivedbinst_DATA = drivedb.h
 endif
+
+knowndrives.lo: drivedb.h
+
+# Create drive database file with updated "VERSION: ..." string using same
+# syntax as on drivedb branches.
+drivedb.h: ../drivedb/drivedb.h Makefile ../include/smartmon/version.sh
+	$(ECHO_V_GEN) ' sed $$(ADD_VERSION) $(top_srcdir)/drivedb/drivedb.h > $@'
+	@. ../include/smartmon/version.sh && \
+	r=$$SMARTMONTOOLS_GIT_REV && d=$$SMARTMONTOOLS_GIT_REV_DATE && \
+	t=$$SMARTMONTOOLS_GIT_REV_TIME && s=$$SMARTMONTOOLS_GIT_SVN_REV && \
+	x="/$$s $$d $$t +0000 $$r" && \
+	if [ "$${r:+y}$${d:+y}$${t:+y}$${s:+y}" != "yyyy" ]; then \
+	  if [ "$$SMARTMONTOOLS_TEST_BUILD" != "1" ]; then \
+	    echo "../include/smartmon/version.sh: missing version information" >&2; \
+	    echo "Use this to override:" >&2; \
+	    echo "export SMARTMONTOOLS_TEST_BUILD=1" >&2; exit 1; \
+	  fi; \
+	  x=" (unknown)"; \
+	fi && \
+	sed 's,^\(  { "VERSION: [1-9][0-9]*\.[0-9][0-9]*\)",\1'"$$x"'",' \
+	  $(top_srcdir)/drivedb/drivedb.h > $@.tmp && \
+	mv -f $@.tmp $@
+
+CLEANFILES = \
+        drivedb.h \
+        drivedb.h.tmp
 
 examples_cpp = \
         examples/ata-standby.cpp \
diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -550,12 +550,12 @@ else
 # Show '-V' output and check drive database syntax
 check:
 	./smartctl -V
-	@echo "./smartctl -B $(top_srcdir)/lib/drivedb.h -P showall >/dev/null"
+	@echo "./smartctl -B ../lib/drivedb.h -P showall >/dev/null"
 	@if ./smartctl -P showall >/dev/null && \
-	    ./smartctl -B $(top_srcdir)/lib/drivedb.h -P showall >/dev/null; then \
-	  echo "$(top_srcdir)/lib/drivedb.h: OK"; \
+	    ./smartctl -B ../lib/drivedb.h -P showall >/dev/null; then \
+	  echo "$../lib/drivedb.h: OK"; \
 	else \
-	  echo "$(top_srcdir)/lib/drivedb.h: Syntax check failed"; exit 1; \
+	  echo "$../lib/drivedb.h: Syntax check failed"; exit 1; \
 	fi
 endif
 
@@ -689,7 +689,7 @@ BINFILES_WIN32 = \
 if ENABLE_DRIVEDB
 BINFILES_WIN32 += \
         os_win32/update-smart-drivedb.ps1 \
-        $(top_srcdir)/lib/drivedb.h
+        ../lib/drivedb.h
 endif
 
 DOCFILES_WIN32 = \
@@ -853,6 +853,7 @@ check-vc-version:
 
 CONFIG_VC_FILES = \
         $(srcdir)/os_win32/vc$(vcver)/config.h \
+        $(srcdir)/os_win32/vc$(vcver)/drivedb.h \
         $(srcdir)/os_win32/vc$(vcver)/smartctl_res.rc \
         $(srcdir)/os_win32/vc$(vcver)/smartd_res.rc \
         $(srcdir)/os_win32/vc$(vcver)/smartmon/smartmon_config.h \
@@ -873,6 +874,12 @@ $(srcdir)/os_win32/vc$(vcver)/config.h: ../config.h Makefile
 	$(ECHO_V_GEN) ' $$(CONFIG_VC_FILTER) < ../config.h > $@.tmp'
 	@$(CONFIG_VC_FILTER) < ../config.h > $@.tmp
 	$(AM_V_at)mv -f $@.tmp $@
+
+$(srcdir)/os_win32/vc$(vcver)/drivedb.h: ../lib/drivedb.h
+	$(AM_V_GEN)cp ../lib/drivedb.h $@
+
+../lib/drivedb.h: ../drivedb/drivedb.h ../lib/Makefile ../include/smartmon/version.sh
+	$(MAKE) -C ../lib drivedb.h
 
 $(srcdir)/os_win32/vc$(vcver)/smartmon/smartmon_config.h: ../include/smartmon/smartmon_config.h Makefile
 	$(ECHO_V_GEN) ' $$(CONFIG_VC_FILTER) < ../include/smartmon/smartmon_config.h > $@.tmp'
